### ISSUE TITLE
How to modify the touched area?

### ISSUE THREAD

**Issue by Sucareto** [SirusDoma/MaiSense#9]
I found this:
https://github.com/SirusDoma/MaiSense/blob/master/src/dllmain.cpp#L39
I modified it to:
sensorChecker.SetScreenSize(300,300);
Now the touch becomes a 300x300 area starting from the upper left corner.
I want to change the starting point to the lower left corner, what should I do?

Sorry, my English is not good and I am using Google Translate.

**Comment by SirusDoma** [comment]
You probably need to configure the [sensor region](https://github.com/SirusDoma/MaiSense/blob/master/include/MaiSense/SensorChecker.hpp#L15-L31). The "region" is the touchable sensor region, those point / coordinates use top-left format based on 1000x1000 window size. You need to recalculate those points.

![](https://user-images.githubusercontent.com/47954501/75342850-554eae00-58eb-11ea-9bfd-cb87d849b651.png)

I believe you will require extra codes to calculate sensor region in sensor checker if you want to adapt other than top-left coordinate system with various window size (e.g you want to support other than 300x300), otherwise just hardcode it there.  

Look at [SensorRegion](https://github.com/SirusDoma/MaiSense/blob/master/include/MaiSense/SensorRegion.hpp) if you want to learn more how MaiSense process touch input collision between these sensors

**Comment by Sucareto** [comment]
Okay, I will check this part of the code.
Do you have plans to support 2p mode?
Change the window resolution to 2160x1920, and modify the 1p touch area to (0,840)~(1079,1919) starting from the upper left corner, nothing more.

**Comment by SirusDoma** [comment]
As stated in README, I have no plan to support 2p mode nor do any further development. Perhaps someday when I'm totally free but don't hold your breath (don't wait for it, can't promise).  

If you familiar with git and want to help the development, please make a pull request, I'll be happy to review it.

**Comment by Sucareto** [comment]
Okay, let me try to read the code first.
